
#ifndef SendingContext_IDL
#define SendingContext_IDL

#include <Corba.idl>

#pragma prefix "omg.org"

module CORBA {
  //
  // The abstract type for runtime representations
  //
  interface RunTime {};

  //
  // The specific code base for implementation repository access
  //
  interface CodeBase : RunTime {

    typedef sequence<CORBA::ValueDef::FullValueDescription> ValueDescSeq;
    typedef string URL;
    typedef sequence<URL> URLSeq;
    
    //
    // acces to implementation repository (Java code base)
    //
    URL implementation (in string id);
    URLSeq implementations (in CORBA::StringSeq ids);
    
    //
    // access to interface repository
    //
    CORBA::StringSeq bases (in string id);
    CORBA::Repository get_ir ();
    CORBA::ValueDef::FullValueDescription meta (in string id);
    ValueDescSeq metas (in string id);
  };

};

#endif
