// File: _orb.idl
// From CORBA 3.0
#ifndef __ORB_IDL_
#define __ORB_IDL_

#ifdef _PRE_3_0_COMPILER_
#pragma prefix "omg.org"
#else
typeprefix CORBA "omg.org"
#endif

#ifdef _PRE_3_0_COMPILER_ 
#ifdef _NO_LOCAL_
#define local
#endif
#endif

module CORBA {
// Forward references, alphabetically
    interface ConstructionPolicy;        // Chapter  4, CORBA_DomainManager.idl
    local interface Current;             // Chapter  4, CORBA_Current.idl
    interface DomainManager;             // Chapter  4, CORBA_DomainManager.idl
    interface Policy;                    // Chapter  4, CORBA_Policy.idl
    local interface PollableSet;         // Chapter  7, CORBA_Pollable.idl
    abstract valuetype CustomMarshal;    // Chapter  5, CORBA_valuetype.idl
    abstract valuetype DataInputStream;  // Chapter  5, CORBA_Stream.idl
    abstract valuetype DataOutputStream; // Chapter  5, CORBA_Stream.idl

// Forward references to Chapter 10, CORBA_InterfaceRepository.idl
    interface AbstractInterfaceDef;
    interface AliasDef;
    interface ArrayDef;
    interface AttributeDef;
    interface ConstantDef;
    interface Contained;
    interface Container;
    interface EnumDef;
    interface ExceptionDef;
    interface ExtInterfaceDef;
    interface ExtValueDef;
    interface ExtAbstractInterfaceDef;
    interface ExtLocalInterfaceDef;
    interface FixedDef;
    interface IDLType;
    interface InterfaceDef;
    interface IRObject;
    interface LocalInterfaceDef;
    interface ModuleDef;
    interface NativeDef;
    interface OperationDef;
    interface PrimitiveDef; 
    interface Repository;
    interface SequenceDef;
    interface StringDef;
    interface StructDef;
    interface TypeCode;
    interface TypedefDef;
    interface UnionDef;
    interface ValueDef;
    interface ValueBoxDef;
    interface ValueMemberDef;
    interface WstringDef;

// Chapter 3: IDL Syntax and Semantics
#include <CORBA_StandardExceptions.idl>

};

#endif // __ORB_IDL_
