From: "Apache Org" <apache@apache.org>
To: "Apache Org" <apache@apache.org>
Subject: Test
Date: Sun, 23 Nov 2014 13:11:29 -0200
Message-ID: <UUUUUUUUUU.apache@apache.org>
MIME-Version: 1.0
Content-Type: text/plain;
	charset=iso-8859-1
Content-Transfer-Encoding: quoted-printable

Er h=F6rte leise Schritte hinter sich. Das bedeutete nichts Gutes. Wer w=FC=
rde ihm schon folgen, sp=E4t in der Nacht und dazu noch in dieser engen Gas=
se mitten im =FCbel beleumundeten Hafenviertel? Gerade jetzt, wo er das Din=
g seines Lebens gedreht hatte und mit der Beute verschwinden wollte! Hatte =
einer seiner zahllosen Kollegen dieselbe Idee gehabt, ihn beobachtet und ab=
gewartet, um ihn nun um die Fr=FCchte seiner Arbeit zu erleichtern? Oder ge=
h=F6rten die Schritte hinter ihm zu einem der unz=E4hligen Gesetzesh=FCter =
dieser Stadt, und die st=E4hlerne Acht um seine Handgelenke w=FCrde gleich =
zuschnappen? Er konnte die Aufforderung stehen zu bleiben schon h=F6ren. Ge=
hetzt sah er sich um. Pl=F6tzlich erblickte er den schmalen Durchgang. Blit=
zartig drehte er sich nach rechts und verschwand zwischen den beiden Geb=E4=
uden.

Beinahe w=E4re er dabei =FCber den umgest=FCrzten M=FClleimer gefallen, der=
 mitten im Weg lag. Er versuchte, sich in der Dunkelheit seinen Weg zu erta=
sten und erstarrte: Anscheinend gab es keinen anderen Ausweg aus diesem kle=
inen Hof als den Durchgang, durch den er gekommen war. Die Schritte wurden =
lauter und lauter, er sah eine dunkle Gestalt um die Ecke biegen. Fieberhaf=
t irrten seine Augen durch die n=E4chtliche Dunkelheit und suchten einen Au=
sweg. War jetzt wirklich alles vorbei, waren alle M=FChe und alle Vorbereit=
ungen umsonst? Er presste sich ganz eng an die Wand hinter ihm und hoffte, =
der Verfolger w=FCrde ihn =FCbersehen, als pl=F6tzlich neben ihm mit kaum w=
ahrnehmbarem Quietschen eine T=FCr im n=E4chtlichen Wind hin und her schwan=
g. K=F6nnte dieses der flehentlich herbeigesehnte Ausweg aus seinem Dilemma=
 sein?

Langsam bewegte er sich auf die offene T=FCr zu, immer dicht an die Mauer g=
epresst. W=FCrde diese T=FCr seine Rettung werden? Er h=F6rte leise Schritt=
e hinter sich. Das bedeutete nichts Gutes. Wer w=FCrde ihm schon folgen, sp=
=E4t in der Nacht und dazu noch in dieser engen Gasse mitten im =FCbel bele=
umundeten Hafenviertel? Gerade jetzt, wo er das Ding seines Lebens gedreht =
hatte und mit der Beute verschwinden wollte! Hatte einer seiner zahllosen K=
ollegen dieselbe Idee gehabt, ihn beobachtet und abgewartet, um ihn nun um =
die Fr=FCchte seiner Arbeit zu erleichtern? Oder geh=F6rten die Schritte hi=
nter ihm zu einem der unz=E4hligen Gesetzesh=FCter dieser Stadt, und die st=
=E4hlerne Acht um seine Handgelenke w=FCrde gleich zuschnappen? Er konnte d=
ie Aufforderung stehen zu bleiben schon h=F6ren. Gehetzt sah er sich um. Pl=
=F6tzlich erblickte er den schmalen Durchgang. Blitzartig drehte er sich na=
ch rechts und verschwand zwischen den beiden Geb=E4uden. Beinahe w=E4re er =
dabei =FCber den umgest=FCrzten M=FClleimer gefallen, der mitten im Weg lag=
. Er versuchte, sich in der Dunkelheit seinen Weg zu ertasten und erstarrte=
: Anscheinend gab es keinen anderen Ausweg aus diesem kleinen Hof als den D=
urchgang, durch den er gekommen war. Die Schritte wurden lauter und lauter,=
 er sah eine dunkle Gestalt um die Ecke biegen. Fieberhaft irrten seine Aug=
en durch die n=E4chtliche Dunkelheit und suchten einen Ausweg. War jetzt wi=
rklich alles vorbei, waren alle M=FChe und alle Vorbereitungen umsonst? Er =
presste sich ganz eng an die Wand hinter ihm und hoffte, der Verfolger w=FC=
rde ihn =FCbersehen, als pl=F6tzlich neben ihm
